"""create financial schema

Revision ID: 2e6e98d8c631
Revises:
Create Date: 2026-08-03 23:14:18.291447

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e6e98d8c631"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre", name="uq_categories_nombre"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("nombres", sa.String(length=150), nullable=False),
        sa.Column("apellidos", sa.String(length=150), nullable=False),
        sa.Column("codigo_estudiante", sa.String(length=50), nullable=True),
        sa.Column("rol", sa.String(length=20), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rol <> 'alumno' OR codigo_estudiante IS NOT NULL",
            name="ck_users_alumno_codigo_estudiante",
        ),
        sa.CheckConstraint(
            "rol IN ('alumno', 'administrador', 'superadministrador')", name="ck_users_rol"
        ),
        sa.CheckConstraint(
            "rol NOT IN ('administrador', 'superadministrador') OR email IS NOT NULL",
            name="ck_users_administrativo_email",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_users_codigo_estudiante_not_null",
        "users",
        ["codigo_estudiante"],
        unique=True,
        postgresql_where=sa.text("codigo_estudiante IS NOT NULL"),
    )
    op.create_index(
        "uq_users_email_normalized",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_table(
        "audit_log",
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("tipo_operacion", sa.String(length=100), nullable=False),
        sa.Column("entidad_tipo", sa.String(length=100), nullable=False),
        sa.Column("entidad_id", sa.Uuid(), nullable=False),
        sa.Column("detalle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("direccion_ip", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["usuario_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_log_entity_created",
        "audit_log",
        ["entidad_tipo", "entidad_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_operation_created",
        "audit_log",
        ["tipo_operacion", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_user_created", "audit_log", ["usuario_id", "created_at"], unique=False
    )
    op.create_table(
        "financial_periods",
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("anio", sa.SmallInteger(), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("closed_by", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("estado IN ('abierto', 'cerrado')", name="ck_financial_periods_estado"),
        sa.CheckConstraint("fecha_inicio < fecha_fin", name="ck_financial_periods_date_range"),
        sa.ForeignKeyConstraint(["closed_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["usuario_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_sessions_expires", "sessions", ["expires_at"], unique=False)
    op.create_index("ix_sessions_user", "sessions", ["usuario_id"], unique=False)
    op.create_table(
        "movements",
        sa.Column("periodo_id", sa.Uuid(), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("categoria_id", sa.Uuid(), nullable=True),
        sa.Column("fuente", sa.String(length=255), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("monto", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("proveedor", sa.String(length=255), nullable=True),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("fecha_movimiento", sa.Date(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("published_by", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("justificacion_anulacion", sa.Text(), nullable=True),
        sa.Column("annulled_by", sa.Uuid(), nullable=True),
        sa.Column("annulled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reemplaza_movimiento_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado != 'anulado' OR (length(btrim(justificacion_anulacion)) > 0 "
            "AND annulled_by IS NOT NULL AND annulled_at IS NOT NULL)",
            name="ck_movements_annulment_metadata",
        ),
        sa.CheckConstraint(
            "estado = 'borrador' OR (published_by IS NOT NULL AND published_at IS NOT NULL)",
            name="ck_movements_publication_metadata",
        ),
        sa.CheckConstraint(
            "estado IN ('borrador', 'publicado', 'anulado')", name="ck_movements_estado"
        ),
        sa.CheckConstraint(
            "tipo != 'ingreso' OR length(btrim(fuente)) > 0", name="ck_movements_ingreso_fuente"
        ),
        sa.CheckConstraint("tipo IN ('ingreso', 'gasto')", name="ck_movements_tipo"),
        sa.CheckConstraint("monto > 0", name="ck_movements_monto_positive"),
        sa.CheckConstraint(
            "reemplaza_movimiento_id IS NULL OR reemplaza_movimiento_id <> id",
            name="ck_movements_replacement_not_self",
        ),
        sa.ForeignKeyConstraint(["annulled_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["categoria_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["periodo_id"], ["financial_periods.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["published_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reemplaza_movimiento_id"], ["movements.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_movements_category", "movements", ["categoria_id"], unique=False)
    op.create_index(
        "ix_movements_period_state_type_date",
        "movements",
        ["periodo_id", "estado", "tipo", "fecha_movimiento"],
        unique=False,
    )
    op.create_table(
        "correction_history",
        sa.Column("movement_id", sa.Uuid(), nullable=False),
        sa.Column("campo", sa.String(length=100), nullable=False),
        sa.Column("valor_anterior", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valor_nuevo", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["movement_id"], ["movements.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["usuario_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_correction_history_movement_created",
        "correction_history",
        ["movement_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "vouchers",
        sa.Column("movement_id", sa.Uuid(), nullable=False),
        sa.Column("nombre_archivo", sa.String(length=255), nullable=False),
        sa.Column("ruta_logica", sa.String(length=1024), nullable=False),
        sa.Column("tipo_mime", sa.String(length=100), nullable=False),
        sa.Column("tamaño", sa.BigInteger(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("replaces_voucher_id", sa.Uuid(), nullable=True),
        sa.Column("motivo_reemplazo", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("replaced_by", sa.Uuid(), nullable=True),
        sa.Column("replaced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sha256", sa.LargeBinary(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "tipo_mime IN ('application/pdf', 'image/jpeg', 'image/png')",
            name="ck_vouchers_tipo_mime",
        ),
        sa.CheckConstraint("tamaño > 0", name="ck_vouchers_size_positive"),
        sa.ForeignKeyConstraint(["movement_id"], ["movements.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["replaced_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["replaces_voucher_id"], ["vouchers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ruta_logica", name="uq_vouchers_ruta_logica"),
    )
    op.create_index("ix_vouchers_movement", "vouchers", ["movement_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vouchers_movement", table_name="vouchers")
    op.drop_table("vouchers")
    op.drop_index("ix_correction_history_movement_created", table_name="correction_history")
    op.drop_table("correction_history")
    op.drop_index("ix_movements_period_state_type_date", table_name="movements")
    op.drop_index("ix_movements_category", table_name="movements")
    op.drop_table("movements")
    op.drop_index("ix_sessions_user", table_name="sessions")
    op.drop_index("ix_sessions_expires", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("financial_periods")
    op.drop_index("ix_audit_log_user_created", table_name="audit_log")
    op.drop_index("ix_audit_log_operation_created", table_name="audit_log")
    op.drop_index("ix_audit_log_entity_created", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(
        "uq_users_email_normalized",
        table_name="users",
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.drop_index(
        "uq_users_codigo_estudiante_not_null",
        table_name="users",
        postgresql_where=sa.text("codigo_estudiante IS NOT NULL"),
    )
    op.drop_table("users")
    op.drop_table("categories")
    # ### end Alembic commands ###
